**Separamos en varios csv, uno por cada columna con el país y el año**

In [11]:
import pandas as pd
df = pd.read_csv('DietComposition.csv', sep=',')
df.drop(columns=['Code'], inplace=True)

In [12]:
df

,Country,Year,Other,Sugar,OilsAndFats,Meat,DairyAndEggs,FruitAndVegetables,StarchyRoots,Pulses,CerealsAndGrains,AlcoholicBeverages
0,Afghanistan,1961,13,51,92,88,102,82,25,16,2530,0.0
1,Afghanistan,1962,12,45,98,88,101,76,22,17,2458,0.0
2,Afghanistan,1963,13,47,106,91,110,79,23,17,2212,0.0
3,Afghanistan,1964,11,55,102,93,110,95,24,18,2445,0.0
4,Afghanistan,1965,13,57,105,95,118,95,24,18,2431,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
8149,Zimbabwe,2009,17,209,345,94,53,28,56,56,1222,67.0
8150,Zimbabwe,2010,19,223,342,94,56,32,54,49,1233,66.0
8151,Zimbabwe,2011,18,232,343,98,59,32,56,39,1257,66.0
8152,Zimbabwe,2012,16,264,353,99,55,31,55,35,1210,79.0
8153,Zimbabwe,2013,14,268,340,91,55,29,54,36,1147,76.0

In [13]:
i = 1
for column in list(df.columns)[2:]:
    df[['Country','Year', column]].rename(columns={column:'Value'}).to_csv(f'55-{i}_DietComposition{column}.csv', sep=',', index=False)
    i+=1